# https://www.playframework.com/documentation/latest/Configuration

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = [
    "http://localhost:3000",
    "https://drp-07.vercel.app"
  ]
  allowedHttpMethods = ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Authorization"]
}

play.modules.enabled += "Module"

play.filters.hosts.allowed = [
  "localhost:9000",
  "127.0.0.1:9000",
  "drp07-production.up.railway.app"
]
