name: CI

on:
  pull_request:
  push:

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint

      - name: Build frontend
        run: npm run build

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Coursier, Java and sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt

      - name: Compile backend
        run: sbt compile

      - name: Lint backend
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile backend tests
        run: sbt Test/compile